name: Monitoramento de Chuvas

on:
  schedule:
    - cron: "0 */2 * * *"      # a cada 2h (UTC)
    - cron: "30 2 * * *"       # rodar HOJE às 23:30 BRT
    - cron: "0 1 * * *"        # diário às 22:00 BRT (01:00 UTC)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        run: node bot.js
