name: Monitoramento de Chuvas

on:
  schedule:
    - cron: "0 */2 * * *"   # roda de 2 em 2h (UTC)
    - cron: "0 1 * * *"     # roda 01:00 UTC = ~22:00 BRT
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        run: node bot.js
