name: Monitor de Chuvas

on:
  schedule:
    - cron: "0 */2 * * *"   # a cada 2 horas (UTC)
  workflow_dispatch:         # permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run script
        run: node bot.js
